default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

development:
  <<: *default
  database: genieacs_gui_development


test:
  <<: *default
  database: genieacs_gui_test

production:
  <<: *default
  database: genieacs_gui
  username: postgres
  password:
